### PR TITLE
Update gameplay gif

### PR DESCRIPTION
**Pull request by ghost**
Text should read as:
Please note that the game might not be playable on certain browsers due to various reasons, such as the browser not displaying the full URL, or not allowing frequent changes, or escaping the Braille characters used in the game display.

Despite the game being a joke, bug reports, ideas, and pull requests are [super welcome](https://github.com/epidemian/snake/issues)!

### CODE REVIEW

**Comment by ghost** [comment]
Edited for grammar.

**Comment by epidemian** [comment]
@elofagoodtime Hey, thanks for the PR. Was there any problem that you decided to close it?

About the grammar change, i have no complaints, in fact "PRs are welcome" kinda sounds more natural than "are welcomed". But English is not my first language and i don't have a very strong grammar justification for either. So, if you have a better command of English than me (which is not a high bar) or are a native speaker, then by all means, lets go with your edit :)

But, besides that, i'm very curious about the other change: the gif recording. What browser/OS were you using? It's been a while since Chrome and Firefox started escaping whitespace characters on URLs, and i thought that the game has been basically dead an unplayable since then.

**Comment by ghost** [comment]
Hi, it’s my first time using GitHub so I wasn’t sure if I did it right. I
was trying to edit but ended up closing it because I was confused. If
English isn’t your first language, I can help edit other things if you’d
like. I’m a native speaker.

I didn’t change the recording, that was someone before me. It wasn’t
playable on chrome.

**Comment by epidemian** [comment]
Ohh i see. I got confused by this PR too :sweat_smile: 

Yeah, for some reason the PR you created is for merging an existing commit (this one a7e71e96336a1bcd644f971ccbc2fbd5da5a3728) that i seem to have made some time ago on a branch called "test".

That's why the changes that are shown here under "Files changed" show the text "are welcomed" being changed to "are welcome", even though the README on the master branch (that you can see [here](https://github.com/epidemian/snake)) already has that text.

Now that i've reread this PR description i see the suggestions you're making are for the other paragraph hehe. I can copy that text myself, but if you're interested in submitting a PR and trying again, please do so. There should be a pencil edit button either on the README [on the homepage of the repo](https://github.com/epidemian/snake#readme) or [here](https://github.com/epidemian/snake/blob/master/README.md). That should allow you to submit a new PR for those text changes. If you need any help you can ping me :)

**Comment by ghost** [comment]
You’re welcome to do it, but I appreciate the offer! I won’t be on my
computer for a few days.

Sorry for the confusion! I’m not used to GitHub yet.

**Pull request closed without merging**
